### ISSUE TITLE
unexpected behaviour "consume_while"

### ISSUE THREAD

**Issue by JonTidswell** [coolbutuseless/flexo#2]
First a small item: the documentation for TokenStream$read_while() says "Consume tokens ..."
I'm thinking this is just a cut-n-paste oversight and easily fixed.

The surprise I had was with the TokenStream$consume_while() function.

It implements the logic
```
do
    consume(1)
while(...)
```

Where I was expecting
```
while(...) {
   consume(1)
}
```

Here is an example 
```
sentence_regexes <- c(
  word        = "\\w+",
  whitespace  = "\\s+",
  fullstop    = "\\.",
  comma       = ","
)
```

Parsing without a leading whitespace
```
sentence1 <- "Hello there, Rstats."
tokens1 <- lex(sentence1, sentence_regexes)
s1 <- TokenStream$new(tokens1)
s1$consume_while("whitespace")
s1$read_values(1)
[1] "there"
```

Parsing with a leading a whitespace
```
# leading space
sentence2 <- " Hello there, Rstats." 
tokens2 <- lex(sentence2, sentence_regexes)
s2 <- TokenStream$new(tokens2)
s2$consume_while("whitespace")
s2$read_values(1)
[1] "Hello"
```

**Comment by coolbutuseless** [comment]
Note to self: don't forget to fix this in `stream-bse-env.R` as well.

**Comment by coolbutuseless** [comment]
Hi @JonTidswell  - thanks for the helpful bug report.
